steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.']

images:
- 'gcr.io/$PROJECT_ID/gcpdevops'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
